Move lint task down in CI, so that the missing test imports are present.
Original error:

```
[lint] tests/unit/parsers/test_iparser.py:3: error: Cannot find implementation or library stub for module named "pytest"  [import]
[lint] tests/unit/parsers/test_iparser.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
[lint] tests/unit/parsers/test_json_parser.py:3: error: Cannot find implementation or library stub for module named "pytest"  [import]
```

Issue: #6.